# LAB 5 : DATA CLEANING

In [8]:
# ! pip install pandas
import pandas as pd
df=pd.read_csv(r"C:\\Users\\HP\\Desktop\\ODD SEM 2026\\DATA SCIENCE LAB\\dirtydata.csv")
print(df)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     str
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.7 KB

In [10]:
# Describe the data
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [12]:
# Prints the first 10 rows of the dataset
print(df.head(10))
print("\n")
# Prints the last 10 rows of the dataset
print(df.tail(10))

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0
5        60  '2020/12/06'    102       127     300.0
6        60  '2020/12/07'    110       136     374.0
7       450  '2020/12/08'    104       134     253.3
8        30  '2020/12/09'    109       133     195.1
9        60  '2020/12/10'     98       124     269.0


    Duration          Date  Pulse  Maxpulse  Calories
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
# Convert the dataframe into string
print(df.to_string())

In [14]:
print(df)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [16]:
# Drop NaN (Not a Number)  values 
#new_df(varibale)--->stored the values----->data frame
new_df=df.dropna()

In [ ]:
print(new_df)

In [19]:
# To change the original df 
# Use 'inplace=True'
df.dropna(inplace=True)
print(df)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [20]:
df.loc[7,'Duration']=45

In [ ]:
print(df)

In [22]:
# for a larger dataset
# take index(header)-->store-->x 
# increment the value of x
# Till the condition becomes false
for x in df.index:
    # if in the location (x: depends on loop)
    # and duration is > 120 
    # in the location x
    # Set the value as 120
    if df.loc[x,"Duration"]> 120:
        df.loc[x,"Duration"]= 120

In [25]:
for x in df.index:
    if df.loc[x,"Duration"] >120:
        df.drop(x,inplace=True)

In [29]:
# Drop the duplicate row
nv=df.duplicated()
new_out=df.loc[nv==True]
print(new_out)
df.drop_duplicates(inplace=True)
print(df.to_string())

    Duration          Date  Pulse  Maxpulse  Calories
12        60  '2020/12/12'    100       120     250.7
    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7         45  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
import pandas as pd
import numpy as np 
# Dictionary 
dict={'First Score':[100,90,np.nan,95],
      'Second Score':[np.nan,45,56,np.nan],
      'Third Score':[np.nan,40,80,98]}
df=pd.DataFrame(dict)
print(df.to_string())
# Returns True if it encounters null value
print(df.isnull())
# Returns False if it encounters null value
print(df.notnull())

In [38]:
print(df)

   First Score  Second Score  Third Score
0        100.0           NaN          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [44]:
# Fill the values with the specific  value

print(df.fillna(0))

   First Score  Second Score  Third Score
0        100.0           0.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [45]:
df

   First Score  Second Score  Third Score
0        100.0           NaN          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [48]:
# Fill the NaN value with mean 
df_mean=df.mean()
print(df_mean)
data_new= df.fillna(df.mean())
print(data_new)

First Score     95.000000
Second Score    50.500000
Third Score     72.666667
dtype: float64
   First Score  Second Score  Third Score
0        100.0          50.5    72.666667
1         90.0          45.0    40.000000
2         95.0          56.0    80.000000
3         95.0          50.5    98.000000

In [49]:
df.dropna()

   First Score  Second Score  Third Score
1         90.0          45.0         40.0

In [ ]:
# Take the user input for dropping of a column 
# df=df.drop(columns='column_name')
#df=df.drop(columns=['col1','col2'......])

In [ ]:
df=pd.read_csv("dirtydata.csv")
print(df)
ip=input("Enter the column to drop")

In [58]:
print(ip)

Pulse

In [60]:
new_df=df.drop(columns=ip)

In [61]:
print(new_df)

    Duration          Date  Maxpulse  Calories
0         60  '2020/12/01'       130     409.1
1         60  '2020/12/02'       145     479.0
2         60  '2020/12/03'       135     340.0
3         45  '2020/12/04'       175     282.4
4         45  '2020/12/05'       148     406.0
5         60  '2020/12/06'       127     300.0
6         60  '2020/12/07'       136     374.0
7        450  '2020/12/08'       134     253.3
8         30  '2020/12/09'       133     195.1
9         60  '2020/12/10'       124     269.0
10        60  '2020/12/11'       147     329.3
11        60  '2020/12/12'       120     250.7
12        60  '2020/12/12'       120     250.7
13        60  '2020/12/13'       128     345.3
14        60  '2020/12/14'       132     379.3
15        60  '2020/12/15'       123     275.0
16        60  '2020/12/16'       120     215.2
17        60  '2020/12/17'       120     300.0
18        45  '2020/12/18'       112       NaN
19        60  '2020/12/19'       123     323.0
20        45  '2020/12/20'       125     243.0
21        60  '2020/12/21'       131     364.2
22        45           NaN       119     282.0
23        60  '2020/12/23'       101     300.0
24        45  '2020/12/24'       132     246.0
25        60  '2020/12/25'       126     334.5
26        60      20201226       120     250.0
27        60  '2020/12/27'       118     241.0
28        60  '2020/12/28'       132       NaN
29        60  '2020/12/29'       132     280.0
30        60  '2020/12/30'       129     380.3
31        60  '2020/12/31'       115     243.0